language: go

go:
  - 1.8

env:
  - NODE_VERSION=node

notifications:
  email:
    recipients:
      - mail@nurlan.co
    on_success: never
    on_failure: change

before_install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

install:
  - go get ./...
  - go get -u github.com/tdewolff/minify/cmd/minify
  - npm install

script:
  - ./scripts/build.sh

deploy:
  provider: heroku
  app: go-chuck
  api_key: $HEROKU
  skip_cleanup: true
